# Site settings
title: GusBricker
email: chris@lapa.com.au
description: "My blog!"
baseurl: ""
url: "http://gusbricker.io"
twitter_username:
github_username: GusBricker
facebook_username:
coffee_address: 574E2ZGZ45MK

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
gems: ["jekyll-paginate"]
