# Site settings
title: pipefail
email: chris@lapa.com.au
name: Chris Lapa
description: "pipefail"
baseurl: ""
url: "http://www.pipefail.io"
twitter_username: Gus_Bricker
github_username: GusBricker
facebook_username:
coffee_address: 574E2ZGZ45MK
timezone: '+1000'

# Build settings
redcarpet:
    extensions: ["lax_spacing", "fenced_code_blocks", "hard_wrap", "tables", "no_intra_emphasis"]
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate", "jekyll-feed"]
