# Site settings
title: Bad Memory
email: chris@lapa.com.au
name: Chris Lapa
description: "Awesome Things"
baseurl: ""
url: "http://gusbricker.io"
twitter_username: Gus_Bricker
github_username: GusBricker
facebook_username:
coffee_address: 574E2ZGZ45MK
timezone: "+10:00"

# Build settings
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate", "jekyll-feed"]
