# Site settings
title: Bad Memory
email: chris@lapa.com.au
description: "Awesome Things"
baseurl: ""
url: "http://gusbricker.io"
twitter_username: Gus_Bricker
github_username: GusBricker
facebook_username:
coffee_address: 574E2ZGZ45MK
timezone: "+10:00"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
gems: ["jekyll-paginate"]
